on: 
  push:
    branches:
    - main
name: Check allowed files
jobs:
  allowed-files:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw2-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Check
      run: Rscript .github/project-allowed-files.R
