on: 
  push:
    branches:
    - main
    paths:
    - 'presentation/presentation.Rmd'
name: Check presentation renders
jobs:
  knit:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw2-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install Missing Packages
      run: |
        missing = checklist::missing_pkgs(dir = "./", glob = "presentation/presentation.Rmd")
        if (length(missing) > 0)
          install.packages(pkgs = missing)
      shell: Rscript {0}
    - name: Check Renders
      run: |
        checklist::check_rmd_renders("presentation/presentation.Rmd")
      shell: Rscript {0}
